#!/usr/bin/env python

# Copyright 2007 Zachary Pincus
# This file is part of CellTool.
# 
# CellTool is free software; you can redistribute it and/or modify
# it under the terms of version 2 of the GNU General Public License as
# published by the Free Software Foundation.


"""Driver script to run the celltool command-line utilities.
"""
import sys
import os
from celltool.command_line import celltool_driver

celltool_driver.main(os.path.basename(sys.argv[0]), sys.argv[1:])